swagger: "2.0"
info:
  description: "API для создания авторов и книг"
  version: "1.0.0"
  title: "Swagger"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
host: "127.0.0.1"
basePath: "/api"
paths:
  /authors:
    post:
      tags:
        - "authors"
      summary: "Add a new authors to the store"
      description: "Add authors"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "AuthorRequestModel"
          description: "New Author request body "
          required: true
          schema:
            $ref: "#/definitions/CreateAuthorRequestModel"
      responses:
        200:
          description: "avtor uspesho sozdan"
        422:
          description: "Error"
          
definitions:
  CreateAuthorRequestModel:
    type: "object"
    required:
      - "name"
    properties:      
      name:
        type: "string"
      year: 
        type: "integer"

      


